CREATE DATABASE FoxmindedDB

GO

USE FoxmindedDB;

CREATE TABLE COURSES 
(
    COURSE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    NAME NVARCHAR(20),
    DESCRIPTION NVARCHAR(50)
)

CREATE TABLE GROUPS 
(
    GROUP_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    COURSE_ID INT,
    NAME NVARCHAR(20),
	FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID) ON DELETE SET NULL
)

CREATE TABLE STUDENTS 
(
    STUDENT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    GROUP_ID INT,
    FIRST_NAME NVARCHAR(20),
    LAST_NAME NVARCHAR(20),
	FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID) ON DELETE SET NULL
)
