USE FoxmindedDB;
SELECT COURSES.NAME as CourceName, STUDENTS.FIRST_NAME, STUDENTS.LAST_NAME
FROM STUDENTS
JOIN GROUPS ON STUDENTS.GROUP_ID = GROUPS.GROUP_ID 
JOIN COURSES ON GROUPS.COURSE_ID = COURSES.COURSE_ID
ORDER BY COURSES.NAME